### ISSUE TITLE
Patch not working

### ISSUE THREAD

**Issue by eddz95** [MysteryDash/Offline-PS4-Remote-Play#6]
Hello, 
I'm getting the following error message everytime:

---------------------------
Something unexpected happened :/
---------------------------
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at PS4_Remote_Play_Patcher.Program.Main()

---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

   --- End of inner exception stack trace ---<---

**Comment by MysteryDash** [comment]
Hello,

Are you using a proxy or something like that ?

-------- Message d'origine --------

**Comment by eddz95** [comment]
No, not using anything.

**Comment by MysteryDash** [comment]
Blind guess but it could be that.. are you using Windows 7 ?

**Comment by eddz95** [comment]
Nope, on Windows 10.
